### PR TITLE
Docker compose app

### PR DESCRIPTION
**Pull request by gcmalloc**
Add the api database into the docker-compose, note that this will only work with a private fork of the api server.

### CODE REVIEW

**Comment by gcmalloc** [comment]
Added README instruction for how to run stuff, could you retry the following command:

```shell
docker-compose stop; docker-compose rm -f && docker volume prune -f && docker-compose up --build
```

Then run the tests

```shell
cd importer && python test_import.py
```

and report on the result ?

**Comment by gperonato** [comment]
The docker-compose works fine (I set my DB at  "127.0.0.1:5433:5432").
However, when I run the `test_import` I get this error:
```
ERROR: for import_integration_test_db_1  Cannot start service db: driver failed programming external connectivity on endpoint import_integration_test_db_1 (fcca37c5788bfbbe05ccaa6b66027aafc903298643cf24ac94f2c533adf17d5b): Bind for 127.0.0.1:5433 failed: port is already allocated
Creating import_integration_test_geoserver_1 ... done
```

It looks like it is starting a new container, so they cannot have the same port.

**Comment by gcmalloc** [comment]
do you have a container lying around bound on that port or a service on
that port ? you can check the list of services that run your machine with
`lsof -nP -iTCP:$PORT | grep LISTEN`

**Comment by gperonato** [comment]
I switched off the containers created by docker-compose. This is what I get when I run the test import:
```
(base) giuseppeperonato@GP-MBP enermaps % cd importer && python test_import.py

loading setup
running ['docker-compose', '--project-directory', '/Users/giuseppeperonato/dev/EnerMaps/enermaps', '--project-name', 'import_integration_test', '--no-ansi', 'down']
Removing network import_integration_test_default
Network import_integration_test_default not found.
running ['docker-compose', '--project-directory', '/Users/giuseppeperonato/dev/EnerMaps/enermaps', '--project-name', 'import_integration_test', '--no-ansi', 'rm']
running ['docker-compose', '--project-directory', '/Users/giuseppeperonato/dev/EnerMaps/enermaps', '--project-name', 'import_integration_test', '--no-ansi', 'up', '--build', '-d', 'geoserver', 'db']
Creating network "import_integration_test_default" with the default driver
Building geoserver
Building db
Creating import_integration_test_geoserver_1 ... 
Creating import_integration_test_db_1        ... 
Creating import_integration_test_geoserver_1 ... done
Creating import_integration_test_db_1        ... done


<Response [201]> enermaps
<Response [201]> geoserver_db
/Users/giuseppeperonato/opt/anaconda3/lib/python3.7/threading.py:219: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53948), raddr=('127.0.0.1', 8000)>
  self._lock = lock
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/giuseppeperonato/opt/anaconda3/lib/python3.7/threading.py:219: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53950), raddr=('127.0.0.1', 8000)>
  self._lock = lock
ResourceWarning: Enable tracemalloc to get the object allocation traceback
test_import.py:39: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53952), raddr=('127.0.0.1', 8000)>
  is_raster=False,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.test_import.py:50: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53955), raddr=('127.0.0.1', 8000)>
  is_raster=True,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.running ['docker-compose', '--project-directory', '/Users/giuseppeperonato/dev/EnerMaps/enermaps', '--project-name', 'import_integration_test', '--no-ansi', 'down']
Stopping import_integration_test_geoserver_1 ... 
Stopping import_integration_test_db_1        ... 
Stopping import_integration_test_db_1        ... done
Stopping import_integration_test_geoserver_1 ... done
Removing import_integration_test_geoserver_1 ... 
Removing import_integration_test_db_1        ... 
Removing import_integration_test_geoserver_1 ... done
Removing import_integration_test_db_1        ... done
Removing network import_integration_test_default

----------------------------------------------------------------------
Ran 2 tests in 72.748s

OK
```

**Comment by gcmalloc** [comment]
Looks ok to me :)

**Pull request merged**
