### PR TITLE
Import in postgis

### PR DESCRIPTION
**Pull request by gcmalloc**
Force the import to go to postgis, the raster are currently not going to postgis at all.

### CODE REVIEW

**Comment by gperonato** [comment]
I get a 201 Response for both cases, but the tiff is not visible in the geoserver nor in the database..
```
(base) giuseppeperonato@GP-MBP importer % python main.py bau_final_energy_consumption_view.gml
<Response [201]>
(base) giuseppeperonato@GP-MBP importer % python main.py hotmaps-cdd_curr.tif                 
<Response [201]>
```
The import of the tiff stays on "pending" here
http://localhost:8000/geoserver/web/wicket/bookmarkable/org.geoserver.importer.web.ImportDataPage?21

**Comment by gcmalloc** [comment]
If you check the import, raster seems to not be supported by the normal import pipeline if the target is postgres. 
The solution is to use pgraster for the import, I'm not sure it will work trough the rest api only.

It seems that access to raster for visualisation is slowled down by postgres for most query, see  for example https://gis.stackexchange.com/questions/222662/why-is-pgraster-much-slower. On the other hand, it speeds up queries aligning vector and raster (typically calculating indicators of LAU/NUTS). Do you want to explore this space further and see where we want to go (have a raster import to geoserver, have a plugin to that import or keep raster as file on disk) ?

**Comment by gperonato** [comment]
You are right, sorry!
Yes, I can do some tests to check the performance of pgraster vs using simple raster files.

**Review by gperonato — COMMENTED** [review]
All good! Maybe raising an error when the format is not supported?

**Comment by gcmalloc** [comment]
Yeah, on the way I actually thought that depending on the raster file, we could keep both around. As the indicator calculation are really slow in hotmaps for surface calculation. 

The geoserver has the capability, with that PR, to load an existing raster into postgres. It should be an additonal step on top of the existing process (import the file trough the api, then load the file from disk into the db.

**Pull request merged**
